<?php

namespace App;


class Post extends Model
{
    public function getRouteKeyName()
    {
        return 'slug'; // TODO: Change the autogenerated stub May be return 'slug' для символьного кода
    }

    public function tags()
    {
        return $this->belongsToMany(Tag::class);
    }

}
