<?php

namespace App;

use App\Events\PostCreated;
use function spec\Prophecy\Promise\functionCallbackFirstArgument;

class Post extends Model
{
//    protected static function boot()
//    {
//        parent::boot(); // TODO: Change the autogenerated stub
//
//        static::created(function($post) {
//            \Mail::to($post->owner->email)->send(
//                new PostCreated($post)
//            );
//        });
//    }

    protected $dispatchesEvents = [
        'created' => PostCreated::class,
        //сюда же добавить Изменение и удаление статьи при создании events
    ];

    public function getRouteKeyName()
    {
        return 'slug'; // TODO: Change the autogenerated stub May be return 'slug' для символьного кода
    }

    public function tags()
    {
        return $this->belongsToMany(Tag::class);
    }

    public function owner()
    {
        return $this->belongsTo(User::class);
    }
}
